from pathlib import Path
import sys
root=Path(sys.argv[1]); p=root/'index.html'; s=p.read_text()
def once(old,new):
 global s
 if s.count(old)!=1: raise RuntimeError('anchor '+str(s.count(old))+' '+old[:60])
 s=s.replace(old,new,1)
once('<div class="field"><label>加班一日預設時數</label><input id="settingDefaultOtHours" type="number" min="0.5" max="24" step="0.5" placeholder="10"><div class="hint">四班二輪預設 10 小時；實際只加班 4 小時時，可在當天另外修改。</div></div>','''<div class="field"><label>加班一日預設時數</label><input id="settingDefaultOtHours" type="number" min="0.5" max="24" step="0.5" placeholder="10"><div class="hint">四班二輪預設 10 小時；實際只加班 4 小時時，可在當天另外修改。</div></div>
<div class="field"><label for="settingOvertimeMode">加班費率</label><select id="settingOvertimeMode"><option value="legal">勞基法標準</option><option value="fixed">固定倍率</option><option value="custom">公司自訂</option></select><div class="hint" id="overtimeModeHint"></div></div>
<div class="field hidden" id="overtimeFixedWrap"><label>固定倍率</label><input id="settingOvertimeFixedRate" type="number" min="1" max="10" step="0.01" placeholder="例如 2"><div class="hint">例如公司所有加班均以 2 倍計算。</div></div>
<div class="field hidden" id="overtimeCustomRegularWrap"><label>公司自訂・平日倍率</label><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="settingOtRegularFirst" type="number" min="1" max="10" step="0.01" aria-label="平日前兩小時倍率"><input id="settingOtRegularLater" type="number" min="1" max="10" step="0.01" aria-label="平日第三至第四小時倍率"></div><div class="hint">左：前 2 小時；右：第 3～4 小時。</div></div>
<div class="field hidden" id="overtimeCustomRestWrap"><label>公司自訂・休息日倍率</label><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px"><input id="settingOtRestFirst" type="number" min="1" max="10" step="0.01"><input id="settingOtRestLater" type="number" min="1" max="10" step="0.01"><input id="settingOtRestOver8" type="number" min="1" max="10" step="0.01"></div><div class="hint">依序：前 2 小時、第 3～8 小時、第 9～12 小時。</div></div>''')
once('<div class="field" id="hoursWrap"><label>時數</label><input id="dialogHours" type="number" min="0" step="0.5" placeholder="例如 8"></div>','''<div class="field hidden" id="overtimeKindWrap"><label>加班日別</label><select id="dialogOvertimeKind"><option value="regular">平日延長工時</option><option value="rest">休息日出勤</option><option value="holiday">國定假日／特別休假出勤</option></select><div class="hint">輪班制依公司實際排定日別選擇，不以星期六、日判定。</div></div><div class="field" id="hoursWrap"><label>時數</label><input id="dialogHours" type="number" min="0" step="0.5" placeholder="例如 8"></div>''')
once("dailyWorkHours:8,defaultOvertimeHours:10,annualUsedHoursByPeriod:{}","dailyWorkHours:8,defaultOvertimeHours:10,overtimeRateMode:'legal',overtimeFixedRate:2,overtimeRegularFirst:4/3,overtimeRegularLater:5/3,overtimeRestFirst:4/3,overtimeRestLater:5/3,overtimeRestOver8:8/3,annualUsedHoursByPeriod:{}")
helpers='''function overtimeRates(){const mode=['legal','fixed','custom'].includes(state.settings.overtimeRateMode)?state.settings.overtimeRateMode:'legal';if(mode==='fixed'){const r=Math.max(1,num(state.settings.overtimeFixedRate)||2);return{mode,regularFirst:r,regularLater:r,restFirst:r,restLater:r,restOver8:r,holiday:r}}if(mode==='custom')return{mode,regularFirst:Math.max(1,num(state.settings.overtimeRegularFirst)||4/3),regularLater:Math.max(1,num(state.settings.overtimeRegularLater)||5/3),restFirst:Math.max(1,num(state.settings.overtimeRestFirst)||4/3),restLater:Math.max(1,num(state.settings.overtimeRestLater)||5/3),restOver8:Math.max(1,num(state.settings.overtimeRestOver8)||8/3),holiday:1};return{mode:'legal',regularFirst:4/3,regularLater:5/3,restFirst:4/3,restLater:5/3,restOver8:8/3,holiday:1}}
function overtimePayForHours(hourly,hours,kind,r=overtimeRates()){const h=Math.max(0,num(hours));if(!h)return 0;if(kind==='holiday')return hourly*h*r.holiday;if(kind==='rest')return hourly*(Math.min(h,2)*r.restFirst+Math.min(Math.max(h-2,0),6)*r.restLater+Math.max(h-8,0)*r.restOver8);return hourly*(Math.min(h,2)*r.regularFirst+Math.max(h-2,0)*r.regularLater)}
function monthlyOvertimePay(y,m,hourly,fallbackHours){const prefix=monthKey(y,m)+'-',rows=Object.entries(state.dayStatus||{}).filter(([d,st])=>d.startsWith(prefix)&&st&&st.type==='overtime');if(rows.length)return rows.reduce((sum,[d,st])=>sum+overtimePayForHours(hourly,st.hours,st.overtimeKind||'regular'),0);return overtimePayForHours(hourly,fallbackHours,'regular')}
function overtimeRateSummary(){const r=overtimeRates();return r.mode==='fixed'?'固定 '+r.regularFirst.toFixed(2)+' 倍':r.mode==='custom'?'公司自訂倍率':'勞基法標準（平日 4/3、5/3；休息日 4/3、5/3、8/3）'}
'''
once('function renderHeroProfile(){',helpers+'function renderHeroProfile(){')
old="const manualOvertimeHours=('overtimeHours' in mm)?num(mm.overtimeHours):0;const overtimeHours=overtimeDays>0?dailyOt:manualOvertimeHours;const base=num(state.settings.baseSalary),shiftPerDay=num(state.settings.shiftAllowancePerDay),shiftAllowance=shiftPerDay*attendance,meal=num(state.settings.mealAllowance),performance=num(state.settings.performanceAllowance),transport=num(state.settings.transportAllowance),otherIncome=num(state.settings.otherIncome),hourly=(base+shiftAllowance+meal+performance)/240*2,otPay=hourly*overtimeHours,gross=base+shiftAllowance+meal+performance+transport+otherIncome+otPay;"
new="const manualOvertimeHours=('overtimeHours' in mm)?num(mm.overtimeHours):0;const overtimeHours=overtimeDays>0?dailyOt:manualOvertimeHours;const base=num(state.settings.baseSalary),shiftPerDay=num(state.settings.shiftAllowancePerDay),shiftAllowance=shiftPerDay*attendance,meal=num(state.settings.mealAllowance),performance=num(state.settings.performanceAllowance),transport=num(state.settings.transportAllowance),otherIncome=num(state.settings.otherIncome),hourly=(base+shiftAllowance+meal+performance)/240,otPay=monthlyOvertimePay(y,m,hourly,overtimeHours),gross=base+shiftAllowance+meal+performance+transport+otherIncome+otPay;"
once(old,new)
once("setWork('settingDefaultOtHours',state.settings.defaultOvertimeHours||10);","""setWork('settingDefaultOtHours',state.settings.defaultOvertimeHours||10);if($('settingOvertimeMode'))$('settingOvertimeMode').value=state.settings.overtimeRateMode||'legal';setWork('settingOvertimeFixedRate',state.settings.overtimeFixedRate||2);setWork('settingOtRegularFirst',state.settings.overtimeRegularFirst||4/3);setWork('settingOtRegularLater',state.settings.overtimeRegularLater||5/3);setWork('settingOtRestFirst',state.settings.overtimeRestFirst||4/3);setWork('settingOtRestLater',state.settings.overtimeRestLater||5/3);setWork('settingOtRestOver8',state.settings.overtimeRestOver8||8/3);const otMode=state.settings.overtimeRateMode||'legal';$('overtimeFixedWrap').classList.toggle('hidden',otMode!=='fixed');$('overtimeCustomRegularWrap').classList.toggle('hidden',otMode!=='custom');$('overtimeCustomRestWrap').classList.toggle('hidden',otMode!=='custom');$('overtimeModeHint').textContent=otMode==='legal'?'平日前 2 小時 4/3、第 3～4 小時 5/3；休息日依分段費率。':otMode==='fixed'?'所有加班時數使用同一倍率。':'可依公司優於法令的制度自行設定各區間倍率。';""")
once("$('dialogStatus').value=selectedType;","$('dialogStatus').value=selectedType;$('dialogOvertimeKind').value=st.overtimeKind||'regular';")
once("$('customLabelWrap').classList.toggle('hidden',t!=='custom');","$('customLabelWrap').classList.toggle('hidden',t!=='custom');$('overtimeKindWrap').classList.toggle('hidden',t!=='overtime');")
once("label:type==='custom'?($('dialogCustomLabel').value.trim()||'自訂假別'):''","label:type==='custom'?($('dialogCustomLabel').value.trim()||'自訂假別'):'',overtimeKind:type==='overtime'?$('dialogOvertimeKind').value:''")
once("● 加班費時薪 ＝（底薪＋本月輪班津貼＋伙食津貼＋表現津貼）÷ 240 × 2 ＝ ${money(mc.hourly)}<br>● 本月加班費 ＝ ${money(mc.hourly)} × ${mc.overtimeHours} 小時 ＝ ${money(mc.otPay)}","● 平日每小時工資額 ＝（底薪＋本月輪班津貼＋伙食津貼＋表現津貼）÷ 240 ＝ ${money(mc.hourly)}<br>● 加班費率 ＝ ${overtimeRateSummary()}<br>● 本月加班費 ＝依逐日加班日別與時數分段計算 ＝ ${money(mc.otPay)}")
anchor="[['settingPayday','payday'],['settingDailyHours','dailyWorkHours'],['settingDefaultOtHours','defaultOvertimeHours'],['settingSickUsedHours','sickUsedHours'],['settingPersonalUsedHours','personalUsedHours']].forEach(([id,key])=>{$(id).oninput=e=>{state.settings[key]=num(e.target.value);changedAndSync();render()}});"
once(anchor,anchor+"\n"+"""$('settingOvertimeMode').onchange=e=>{state.settings.overtimeRateMode=e.target.value||'legal';changedAndSync();render()};[['settingOvertimeFixedRate','overtimeFixedRate'],['settingOtRegularFirst','overtimeRegularFirst'],['settingOtRegularLater','overtimeRegularLater'],['settingOtRestFirst','overtimeRestFirst'],['settingOtRestLater','overtimeRestLater'],['settingOtRestOver8','overtimeRestOver8']].forEach(([id,key])=>{$(id).oninput=e=>{const v=Number(e.target.value);if(Number.isFinite(v)&&v>=1){state.settings[key]=v;changedAndSync();render()}}});""")
s=s.replace('manifest.webmanifest?v=97','manifest.webmanifest?v=98').replace('介面 v97','介面 v98').replace('meow-sw-reloaded-v97','meow-sw-reloaded-v98').replace('./sw.js?v=97','./sw.js?v=98')
for n in ['settingOvertimeMode','dialogOvertimeKind','monthlyOvertimePay']: assert n in s
p.write_text(s)
sw=root/'sw.js'; w=sw.read_text().replace('meow-work-pwa-v97','meow-work-pwa-v98').replace('manifest.webmanifest?v=97','manifest.webmanifest?v=98');sw.write_text(w)
print('v98 applied')
\n